[package]
name = "experiment"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
simple_logger = "4.0.0"
log = "0.4" # Add this line!
mini-redis = "0.4"
futures = "0.3"